<?php 
    function bda_hello_theme($existing, $type, $theme, $path) {
      return [
      'bda-hello-template' => [
        'variables' => ['test_var' => NULL],
       ],
    ];
    }

    function bda_hello_form_alter(&$form, $form_state, $form_id) {
        // global $user;
        // if ($form_id) {}
        return [
            'bda-gello-form-template' => [
            //   'variables' => ['form' => $form, 'state' => $form_state, 'id' => $form_id],
            ],
          ];
    }